import test from 'node:test';
import assert from 'node:assert/strict';
import {DungeonGenerator,WIDTH,HEIGHT,walkable,canStep,key,DIRS} from '../src/core/DungeonGenerator.js';
import {GameState} from '../src/core/GameState.js';
import {SaveManager} from '../src/core/SaveManager.js';
import {Enemy} from '../src/core/Enemy.js';
function rng(seed){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function fresh(seed=12){const data=new Map();const storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};return new GameState(new SaveManager(storage),rng(seed));}
function checkActors(g){const r=g.run;if(!r)return;const all=[r.player,...r.dungeon.enemies,...(r.companion?[r.companion]:[])];assert.equal(new Set(all.map(e=>key(e.x,e.y))).size,all.length);for(const e of all)assert.ok(walkable(r.dungeon,e.x,e.y));}
test('1,000 generated floors have reachable stairs, all floors connected, and unique spawns',()=>{
 for(let seed=1;seed<=100;seed++)for(let f=1;f<=10;f++){const d=new DungeonGenerator(rng(seed*100+f)).generate(f);const queue=[d.start],seen=new Set([key(d.start.x,d.start.y)]);for(let i=0;i<queue.length;i++)for(const v of DIRS.slice(0,4)){const p={x:queue[i].x+v.x,y:queue[i].y+v.y};const k=key(p.x,p.y);if(walkable(d,p.x,p.y)&&!seen.has(k)){seen.add(k);queue.push(p);}}assert.ok(seen.has(key(d.stairs.x,d.stairs.y)));assert.equal(seen.size,d.tiles.flat().filter(Boolean).length);const actors=[d.start,...d.enemies];assert.equal(new Set(actors.map(e=>key(e.x,e.y))).size,actors.length);assert.ok(d.enemies.every(e=>walkable(d,e.x,e.y)));}
});
test('idle and invalid actions do not advance; successful actions advance exactly once',()=>{const g=fresh();g.start();const r=g.run;const before=structuredClone(r);assert.deepEqual(structuredClone(r),before);g.turns.perform({type:'nope'});assert.equal(r.turn,0);g.turns.perform({type:'wait'});assert.equal(r.turn,1);g.turns.busy=true;assert.equal(g.turns.perform({type:'wait'}),false);assert.equal(r.turn,1);});
test('wall and diagonal corner blocking includes flying wall destinations',()=>{const d={tiles:[[0,0,0],[0,1,0],[0,0,1]]};assert.equal(canStep(d,{x:1,y:1},{x:2,y:2}),false);assert.equal(canStep(d,{x:1,y:1},{x:2,y:2},true),true);assert.equal(canStep(d,{x:1,y:1},{x:2,y:1},true),false);});
test('combat, leveling, inventory capacity, equipment, food and taming',()=>{const g=fresh();g.start();const r=g.run,p=r.player;r.dungeon.enemies=[];const e=new Enemy('slime',1,p.x+1,p.y,'test');r.dungeon.tiles[e.y][e.x]=1;r.dungeon.enemies.push(e);e.hp=1;e.xp=25;g.turns.perform({type:'move',dx:1,dy:0});assert.equal(r.dungeon.enemies.length,0);assert.ok(p.level>1);p.inventory=[{type:'food',power:1}];p.hunger=10;g.turns.perform({type:'item',index:0,mode:'use'});assert.equal(p.hunger,55);p.inventory=[{type:'sword',power:6}];g.turns.perform({type:'item',index:0,mode:'use'});assert.equal(p.equipment.sword.power,6);p.inventory=Array.from({length:16},()=>({type:'stone',power:1}));r.dungeon.loot.push({x:p.x,y:p.y,type:'potion',power:1});g.pickup();assert.equal(p.inventory.length,16);assert.ok(r.dungeon.loot.some(i=>g.at(i,p)));g.random=()=>0;const pet=new Enemy('raptor',1,p.x+1,p.y,'pet');r.dungeon.enemies=[pet];p.inventory=[{type:'meat',power:1}];p.facing={x:1,y:0};g.turns.perform({type:'item',index:0,mode:'use'});assert.equal(r.companion.type,'raptor');checkActors(g);});
test('death retains rewards, gear, recruits; save restores town and active dungeon',()=>{const g=fresh();g.start();g.run.coins=100;g.run.player.inventory.push(...Array.from({length:3},()=>({type:'potion',power:1})));g.run.eggs=1;g.run.recruited=['raptor'];g.persist();const restored=new GameState(g.save);assert.deepEqual(restored.run,structuredClone(g.run));g.finish(false);assert.equal(g.town.coins,60);assert.equal(g.town.eggs,1);assert.equal(g.town.storage.length,3);assert.equal(g.town.dinosaurs[0].type,'raptor');const again=new GameState(g.save);assert.equal(again.run,null);assert.equal(again.town.coins,60);g.result=null;g.start();assert.equal(g.run.floor,1);});
test('actual stair route through ten floors reaches victory',()=>{const g=fresh();g.start();for(let floor=1;floor<=10;floor++){const r=g.run;assert.equal(r.floor,floor);r.dungeon.enemies=[];r.dungeon.house=null;let count=0;while(!g.at(r.player,r.dungeon.stairs)&&count++<500){const next=g.nextStep(r.player,r.dungeon.stairs);assert.ok(next);g.turns.perform({type:'move',dx:next.x-r.player.x,dy:next.y-r.player.y});}assert.ok(count<500);g.turns.perform({type:'inspect'});}assert.equal(g.run,null);assert.equal(g.result.clear,true);assert.equal(g.town.clears,1);});
test('long randomized simulations never overlap actors or walk through walls',()=>{for(let seed=1;seed<=20;seed++){const g=fresh(seed);g.start();for(let n=0;n<250;n++){if(!g.run)break;g.run.player.hp=500;g.run.player.maxHp=500;const v=DIRS[Math.floor(g.random()*8)];g.turns.perform({type:'move',dx:v.x,dy:v.y});checkActors(g);}}});
test('monster house fires once, spawns safely, and starvation can end a run',()=>{const g=fresh();g.start();const r=g.run;r.dungeon.house={roomIndex:0,triggered:false};g.triggerHouse();const n=r.dungeon.enemies.length;g.triggerHouse();assert.equal(r.dungeon.enemies.length,n);checkActors(g);r.dungeon.enemies=[];r.player.hunger=0;r.player.hp=1;r.turn=2;g.turns.perform({type:'wait'});assert.equal(g.run,null);assert.equal(g.result.clear,false);});
test('corrupt or unavailable storage fails gracefully',()=>{const s=new SaveManager({getItem:()=>'{bad',setItem:()=>{throw Error('quota');}});assert.equal(s.load(),null);assert.ok(s.error);assert.equal(s.save({town:{},run:null}),false);assert.ok(s.error);});
test('each companion type follows safely across floors and after save restoration',()=>{
 for(const type of ['raptor','ankylo','ptera']){
  const g=fresh(48);g.town.dinosaurs=[{id:type,type,level:1}];g.town.selected=type;g.start();
  for(let floor=1;floor<=10;floor++){
   g.enterFloor(floor);checkActors(g);
   for(let n=0;n<50;n++){g.run.player.hp=999;const v=DIRS[Math.floor(g.random()*8)];g.turns.perform({type:'move',dx:v.x,dy:v.y});checkActors(g);}
  }
  g.persist();const again=new GameState(g.save);again.turns.perform({type:'wait'});checkActors(again);
 }
});

test('immediate retreats cannot mint items or JP and return packed supplies',()=>{const g=fresh();for(let i=0;i<3;i++){g.start();g.finish(false);}assert.equal(g.town.points,0);assert.equal(g.town.storage.length,0);g.town.storage.push({type:'scroll',power:1});g.start();g.pack(0);g.finish(false);assert.deepEqual(g.town.storage,[{type:'scroll',power:1}]);});
test('denied localStorage getter does not prevent startup',()=>{const original=Object.getOwnPropertyDescriptor(globalThis,'localStorage');try{Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('SecurityError');}});const save=new SaveManager();const g=new GameState(save);g.start();assert.ok(g.run);assert.ok(save.error);}finally{if(original)Object.defineProperty(globalThis,'localStorage',original);else delete globalThis.localStorage;}});
