import {installTouchGuards} from './ui/TouchGuards.js';
import {GameState,CAPACITY} from './core/GameState.js';
import {SaveManager} from './core/SaveManager.js';
import {Player} from './core/Player.js';
import {ITEMS,label} from './core/Item.js';
import {SPECIES} from './core/Enemy.js';
import {Renderer,townArt} from './ui/Renderer.js';
import {Sound} from './ui/Sound.js';
const $=s=>document.querySelector(s),game=new GameState(new SaveManager()),sound=new Sound();
const renderer=new Renderer($('#map'),$('#minimap'),game),dialog=$('dialog');
let bannerTimer,lastAction=-Infinity;
function modal(title,body){$('#modal-title')?.remove();$('#dialog-content').innerHTML=`<h2 id="modal-title">${title}</h2>${body}`;dialog.setAttribute('aria-labelledby','modal-title');if(!dialog.open)dialog.showModal();}
function close(){dialog.close();}
function update(){
 $('#adventure').hidden=!game.run;$('#town').hidden=!!game.run;
 $('#save-error').textContent=game.save.error;
 if(game.run){const r=game.run,p=r.player;$('#stats').innerHTML=`<div class="stat"><small>❤️ HP <span class="${p.hp<p.maxHp*.3?'low':''}">${p.hp}/${p.maxHp}</span></small><div class="hpbar"><i style="width:${100*p.hp/p.maxHp}%"></i></div></div><div class="stat"><small>🍞 おなか</small><b class="${p.hunger<20?'low':''}">${p.hunger}</b></div><div class="stat"><small>LV ${p.level}</small><b>地下${r.floor}階</b></div>`;$('#messages').textContent=r.messages.slice(-2).join('　');renderer.draw();}
 else renderTown();
 for(const e of game.events){sound.play(e.type);renderer.effect(e);if(['level','house','stairs'].includes(e.type)){const text=e.type==='level'?'✨ パワーアップ！':e.type==='house'?'⚠️ モンスターハウス！':`地下${game.run?.floor||10}階`;$('#banner').textContent=text;$('#banner').classList.add('show');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('#banner').classList.remove('show'),1500);}if(e.type==='damage'){$('.map-wrap').classList.remove('shake');void $('.map-wrap').offsetWidth;$('.map-wrap').classList.add('shake');}}
 game.events=[];
 if(game.result&&!dialog.open)showResult();
}
function act(action){if(dialog.open||!game.run)return;const now=performance.now();if(now-lastAction<125)return;lastAction=now;game.turns.perform(action);update();}
function renderTown(){const t=game.town;$('#town').innerHTML=`<div class="town-head"><div class="eyebrow">JO TOWN</div><h1>ジョータウン</h1><p>おかえり！ 次はどんな冒険にする？</p></div><canvas class="town-art" id="town-art" aria-label="ジョーと恐竜たち"></canvas><div class="wallet"><span>🪙 ${t.coins}</span><span>⭐ ${t.points} JP</span><span>🥚 ${t.eggs}</span><span>最高 地下${t.best}階</span></div><button class="primary wide" id="depart">🧭 ダンジョンへ！</button><div class="town-grid"><button id="storage">🎒 もちもの<small>倉庫・そうびを変える</small></button><button id="ranch">🦕 恐竜ひろば<small>いっしょに行く仲間を選ぶ</small></button><button id="shop">🛍 おみせ<small>コインでお買いもの</small></button><button id="training">🌟 たんけん教室<small>ジョーポイントで強くなる</small></button></div><p class="info">1回動くと、敵も1回動くよ。考えているあいだは安心！<br>倒れても、そうび・道具3つ・コインの60%は持ち帰れるよ。</p>`;townArt($('#town-art'));
 $('#depart').onclick=()=>{game.start();update();if(game.town.storage.length)packing();};$('#storage').onclick=storage;$('#ranch').onclick=ranch;$('#shop').onclick=shop;$('#training').onclick=training;}
function showResult(){const r=game.result;modal(r.clear?'おたから発見！ 大ぼうけん成功！':'今回はここまで！',`<div class="result"><div class="big">${r.clear?'🏆':'🌈'}</div><p>地下${r.floor}階まで がんばったね！</p><p>🪙 ${r.coins}コイン　⭐ ${r.points} JP<br>🎒 道具${r.items}こ　🥚 ${r.eggs}こ を持ち帰ったよ。</p><p>そうびと、仲良くなった恐竜も待っているよ。</p><button class="primary wide" id="return-town">ジョータウンへ</button></div>`);$('#return-town').onclick=()=>{game.result=null;game.persist();close();update();};}
function inventory(){const p=game.run.player;modal(`🎒 どうぐ ${p.inventory.length}/${CAPACITY}`,`<p class="info">⚔️ ${Player.attack(p)}　🛡 ${Player.defense(p)}　経験値 ${p.xp}/${Player.threshold(p)}<br>装備：${label(p.equipment.sword)} / ${label(p.equipment.shield)}<br>使う・投げる・置くと、敵も動くよ。投げる方向は黄色い矢印。</p>${p.inventory.map((i,n)=>`<div class="item"><div class="item-title">${ITEMS[i.type].icon} ${label(i)}</div><p>${ITEMS[i.type].description}</p><div class="item-actions"><button data-item="${n}" data-mode="use">${['sword','shield'].includes(i.type)?'そうび':'使う'}</button><button data-item="${n}" data-mode="throw">投げる</button><button data-item="${n}" data-mode="drop">置く</button></div></div>`).join('')||'<p>かばんは空っぽだよ。</p>'}`);dialog.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{close();game.turns.perform({type:'item',index:Number(b.dataset.item),mode:b.dataset.mode});update();});}
function storage(){const t=game.town;modal('🎒 もちもの・そうび',`<p>そうび：${label(t.equipment.sword)} / ${label(t.equipment.shield)}</p><p class="info">道具は出発するときに、かばんへ入れられるよ。</p>${t.storage.map((i,n)=>`<div class="item">${ITEMS[i.type].icon} ${label(i)} ${['sword','shield'].includes(i.type)?`<button data-equip="${n}">そうび</button>`:''}</div>`).join('')||'<p>冒険で道具を持ち帰ろう！</p>'}`);dialog.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{game.townAction('equip',+b.dataset.equip);storage();});}
function packing(){modal('🎒 持っていく道具',`<p>かばん ${game.run.player.inventory.length}/${CAPACITY}。準備ができたら「とじる」で出発！</p>${game.town.storage.map((i,n)=>`<div class="item">${ITEMS[i.type].icon} ${label(i)} <button data-pack="${n}" ${game.run.player.inventory.length>=CAPACITY?'disabled':''}>持っていく</button></div>`).join('')||'<p>ぜんぶかばんに入ったよ。</p>'}`);dialog.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{game.pack(+b.dataset.pack);packing();});}
function ranch(){const t=game.town;const traits={raptor:'攻撃が得意！ 身軽だけど守りはひかえめ。',ankylo:'ゆっくり歩く、かたい守りの仲間。',ptera:'ななめのすきまを飛んで移動できるよ。'};modal('🦕 恐竜ひろば',`<p>🥚 タマゴ ${t.eggs}こ　🪙 ${t.coins}</p><button id="hatch" ${t.eggs?'':'disabled'}>タマゴをかえす</button>${t.dinosaurs.map((d,n)=>`<div class="item"><b>${SPECIES[d.type].name} LV ${d.level} ${t.selected===d.id?'♥ いっしょに行く':''}</b><p>${traits[d.type]}</p><div class="item-actions"><button data-pet="${n}">仲間に選ぶ</button><button data-grow="${n}" ${t.coins<30?'disabled':''}>育てる 🪙30</button></div></div>`).join('')||'<p>恐竜に肉をあげて仲良くなろう！</p>'}<button class="wide" id="solo">ひとりで行く</button>`);$('#hatch').onclick=()=>{game.townAction('hatch');ranch();update();};$('#solo').onclick=()=>{game.townAction('select',-1);ranch();};dialog.querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>{game.townAction('select',+b.dataset.pet);ranch();});dialog.querySelectorAll('[data-grow]').forEach(b=>b.onclick=()=>{game.townAction('petTrain',+b.dataset.grow);ranch();update();});}
function shop(){modal('🛍 おみせ',`<p>🪙 ${game.town.coins}コイン</p><p>げんきジュースを倉庫にお届け！</p><button id="buy" ${game.town.coins<20?'disabled':''}>🧃 ジュースを買う 🪙20</button>`);$('#buy').onclick=()=>{game.townAction('buy');shop();update();};}
function training(){const t=game.town,cost=30+t.training*20;modal('🌟 たんけん教室',`<p>⭐ ${t.points} JP　練習 ${t.training}/10</p><p>次の冒険から、最大HPが3増えるよ。</p><button id="train" ${t.points<cost||t.training>=10?'disabled':''}>れんしゅうする ⭐${cost}</button>`);$('#train').onclick=()=>{game.townAction('train');training();update();};}
$('#sound').onclick=()=>{$('#sound').textContent=sound.toggle()?'音 ON':'音 OFF';};
$('#close-dialog').onclick=()=>{if(game.result){game.result=null;game.persist();}close();update();};
dialog.addEventListener('cancel',()=>{if(game.result){game.result=null;game.persist();}});
$('#bag').onclick=inventory;$('#pause').onclick=()=>{modal('⏸ ひと休み',`<p>冒険は自動で保存されているよ。<br>何もしなければ、敵も動かないよ。</p><p class="info">キーボード：矢印 / WASDで移動<br>Q・E・Z・Cでななめ移動<br>Space：攻撃　I：道具　F：足元　.：待つ</p><button id="retreat">冒険を切り上げて帰る</button>`);$('#retreat').onclick=()=>{modal('町へ帰る？','<p>そうび・道具3つ・コインの60%を持ち帰るよ。</p><button class="wide" id="confirm-return">持ち帰って町へ</button>');$('#confirm-return').onclick=()=>{close();game.finish(false);update();};};};
document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{const [dx,dy]=b.dataset.move.split(',').map(Number);act({type:'move',dx,dy});}));
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act({type:b.dataset.action})));
const keys={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],q:[-1,-1],e:[1,-1],z:[-1,1],c:[1,1],'7':[-1,-1],'8':[0,-1],'9':[1,-1],'4':[-1,0],'6':[1,0],'1':[-1,1],'2':[0,1],'3':[1,1]};
document.addEventListener('keydown',e=>{if(!game.run||dialog.open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(keys[k]||[' ','i','f','.','5'].includes(k))e.preventDefault();if(e.repeat)return;if(keys[k])act({type:'move',dx:keys[k][0],dy:keys[k][1]});else if(k===' ')act({type:'attack'});else if(k==='i')inventory();else if(k==='f')act({type:'inspect'});else if(k==='.'||k==='5')act({type:'wait'});});
// One click is one action. No pointerdown+click pair or held-key repeat.
installTouchGuards(document);
document.addEventListener('visibilitychange',()=>{if(document.hidden)game.persist();});window.addEventListener('pagehide',()=>game.persist());
update();
